# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: \\.coverage
default_language_version:
  python: python3.7

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
        - --fix=no
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: "Black"
        entry: pipenv run black --check
        language: system
        types: ["file", "python", "text"]

      - id: flake8
        name: "Flake8"
        entry: pipenv run flake8
        language: system
        types: ["file", "python", "text"]

      - id: isort
        name: "isort"
        entry: pipenv run isort --check --filter-files
        language: system
        types: ["file", "python", "text"]

      - id: missing-migrations
        name: 'Missing migrations'
        entry: pipenv run ./manage.py makemigrations --check
        language: system
        types: ["file", "python", "text"]
        pass_filenames: false

      # This test fails if web server is not running
      - id: coverage-test
        name: 'Run Django tests'
        entry: pipenv run coverage run manage.py test --noinput --keepdb
        language: system
        types: ["file", "python", "text"]
        pass_filenames: false
        require_serial: true

      - id: coverage-report
        name: 'Confirm test coverage'
        entry: pipenv run coverage report -m --fail-under 98
        language: system
        types: ["file", "python", "text"]
        pass_filenames: false
        require_serial: true
